module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'introduction'
        }
      ]
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'features'
        }
      ]
    },
    {
      type: 'category',
      label: 'API References',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Classes',
          items: [
            {
              type: 'autogenerated',
              dirName: 'classes'
            }
          ]
        },
        {
          type: 'category',
          label: 'Types and Interfaces',
          items: [
            {
              type: 'autogenerated',
              dirName: 'types-interfaces'
            }
          ]
        },
        {
          type: 'category',
          label: 'Exceptions',
          items: [
            {
              type: 'autogenerated',
              dirName: 'exceptions'
            }
          ]
        },
        {
          type: 'category',
          label: 'Decorators',
          items: [
            {
              type: 'autogenerated',
              dirName: 'decorators'
            }
          ]
        },
        {
          type: 'category',
          label: 'Services',
          items: [
            {
              type: 'autogenerated',
              dirName: 'services'
            }
          ]
        }
      ]
    }
  ]
};
